[tool.pylint]
disable = [
  "missing-docstring",
  "unused-import",
  "line-too-long",
]

[tool.pyright]
pythonVersion = "3.13"
typeCheckingMode = "basic"
include = ["."]
exclude = ["**/__pycache__"]
